### ISSUE TITLE
spring-jaeger-cloud-starter:3.2.2 not compatible org.springframework.cloud:spring-cloud-dependencies:2020.0.0

### ISSUE THREAD

**Issue by wesleyjconnorsesame** [opentracing-contrib/java-spring-jaeger#117]
Using    ` implementation "io.opentracing.contrib:opentracing-spring-jaeger-cloud-starter:3.2.2"` I upgraded to the new   `mavenBom "org.springframework.cloud:spring-cloud-dependencies:2020.0.0"`

spring-cloud 'Hoxton.SR89' worked correctly

Since then I get the following error on startup. 
It seems ribbon was removed from spring cloud but is required by jaeger (but not included) with spring-jaeger

Removing spring-jaeger and the new 2020 works correctly

Is there a workaround for this until the versions are updated?

```
Caused by:
  java.lang.NoClassDefFoundError: org/springframework/cloud/openfeign/ribbon/LoadBalancerFeignClient
      at io.opentracing.contrib.spring.cloud.feign.TracedFeignBeanFactory.from(TracedFeignBeanFactory.java:40)
      at io.opentracing.contrib.spring.cloud.feign.TraceFeignContext.addTracingClient(TraceFeignContext.java:64)
      at io.opentracing.contrib.spring.cloud.feign.TraceFeignContext.getInstance(TraceFeignContext.java:46)
      at org.springframework.cloud.openfeign.FeignClientFactoryBean.get(FeignClientFactoryBean.java:272)
      at org.springframework.cloud.openfeign.FeignClientFactoryBean.feign(FeignClientFactoryBean.java:99)
      at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:325)
      at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:315)
      at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
     ... 149 more
```

**Comment by geoand** [comment]
I don't think there are any workarounds at the moment.

We'll need to bump to the new Spring Cloud stuff. Do you want to provide a PR?

**Comment by wesleyjconnorsesame** [comment]
I believe this should actually be in the https://github.com/opentracing-contrib/java-spring-cloud repository as it has direct spring-cloud dependencies
