### ISSUE TITLE
spring boot version 3.0.0 not working with jaeger

### ISSUE THREAD

**Issue by prasad5252** [opentracing-contrib/java-spring-jaeger#146]
i am using jaeger with spring boot version 3.0.0 and java version 17 but unable to discover any services that registered with jaeger UI, is there version issue ? jaeger doen't support spring boot 3.0.0 ?

**Comment by onyn** [comment]
Spring boot 3.0 [removes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files) support of [spring.factories](https://github.com/opentracing-contrib/java-spring-jaeger/blob/f0a5191dbd7a6aeef3e9786655e16086593c1ba0/opentracing-spring-jaeger-starter/src/main/resources/META-INF/spring.factories).

As temporary workaround you may create plain text file `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` and put `io.opentracing.contrib.java.spring.jaeger.starter.JaegerAutoConfiguration` into it.

**Comment by tweetysat** [comment]
I'm uisng Spring boot 3.0.0 and 

        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
            <version>3.3.1</version>
        </dependency>
        
I also added the file like @onyn suggested

![2023-01-30 10_23_34-ScanOutputHandler – org springframework boot autoconfigure AutoConfiguration imp](https://user-images.githubusercontent.com/16302367/215438405-2c87e1ba-9b16-43cf-9d75-e7e32a3ad2e7.png)

But my application is still not starting.

```
10:21:26.789 [restartedMain] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.UnsupportedOperationException: null
	at java.base/java.util.Collections$UnmodifiableMap.put(Collections.java:1505)
	at io.opentracing.contrib.spring.cloud.async.TraceEnvironmentPostProcessor.addOrReplace(TraceEnvironmentPostProcessor.java:64)
	at io.opentracing.contrib.spring.cloud.async.TraceEnvironmentPostProcessor.postProcessEnvironment(TraceEnvironmentPostProcessor.java:52)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:352)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
	at be.fgov.minfin.soh.dispatcher.mailbox.MailboxDispatcherApplication.main(MyApp.java:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

```

**Comment by tweetysat** [comment]
I'm using spring boot 3.0.0 and

        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-spring-jaeger-web-starter</artifactId>
            <version>3.3.1</version>
        </dependency>

As @onyn suggested I tried adding that file in my project but it is not working.

The only way I found to have something happening is to add

    @Component
    public class JaegerConfiguration {

        @Bean
        public static JaegerTracer jaegerTracer(
                @Value("${spring.application.name}") String serviceName
        ) {
            return new Configuration(serviceName)
                    .withSampler(new io.jaegertracing.Configuration.SamplerConfiguration().withType(ConstSampler.TYPE).withParam(1))
                    .withReporter(new io.jaegertracing.Configuration.ReporterConfiguration().withLogSpans(true))
                    .getTracer();
        }

    }

Now I can see

    2023-02-01T11:59:30.120+01:00  INFO 12392 --- [  restartedMain] io.jaegertracing.Configuration           : Initialized tracer=JaegerTracer(version=Java-1.3.2, serviceName=mailbox-dispatcher, reporter=CompositeReporter(reporters=[RemoteReporter(sender=UdpSender(host=localhost, port=6831), closeEnqueueTimeout=1000), LoggingReporter(logger=Logger[io.jaegertracing.internal.reporters.LoggingReporter])]), sampler=ConstSampler(decision=true, tags={sampler.type=const, sampler.param=true}), tags={hostname=xxx, jaeger.version=Java-1.3.2, ip=xxx}, zipkinSharedRpcSpan=false, expandExceptionLogs=false, useTraceId128Bit=false)

BUT .... I don't konw how to use a http-sender in place of a udp-sender and change the url.

I tried adding 

    opentracing:
      jaeger:
        enabled: true
        http-sender:
          url: http://myurl:14268/api/traces

But it always tells me `reporter=CompositeReporter(reporters=[RemoteReporter(sender=UdpSender(host=localhost, port=6831)`

**Comment by akshayrana30** [comment]
Can also use this in one of the config classes. 
```
@ImportAutoConfiguration(io.opentracing.contrib.java.spring.jaeger.starter.JaegerAutoConfiguration.class)
```

**Comment by kayeanni** [comment]
I am facing the same problem, were you able to make it work?

**Comment by onyn** [comment]
@kayeanni, switch from jaeger to [micrometer tracing](https://spring.io/blog/2022/10/12/observability-with-spring-boot-3). This is best solution in long term.

See also https://github.com/opentracing-contrib/java-spring-jaeger/pull/148#issuecomment-1548497689
