### ISSUE TITLE
opentracing.spring.cloud.log.enabled  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by wintermin** [opentracing-contrib/java-spring-jaeger#41]
when i use opentracing-spring-jaeger-cloud-starter 0.2.1 ，opentracing-spring-cloud-starter is 0.1.15 ，opentracing.spring.cloud.log.enabled =true,  have a bug . bug info 
Exception in thread "jaeger.RemoteReporter-QueueProcessor" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at io.jaegertracing.thrift.internal.reporters.protocols.JaegerThriftSpanConverter.buildLogs(JaegerThriftSpanConverter.java:76)
	at io.jaegertracing.thrift.internal.reporters.protocols.JaegerThriftSpanConverter.convertSpan(JaegerThriftSpanConverter.java:58)
	at io.jaegertracing.thrift.internal.senders.ThriftSender.append(ThriftSender.java:54)
	at io.jaegertracing.internal.reporters.RemoteReporter$AppendCommand.execute(RemoteReporter.java:138)
	at io.jaegertracing.internal.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:171)
	at java.lang.Thread.run(Thread.java:748)

**if  opentracing.spring.cloud.log.enabled=false  will be ok**

**Comment by wintermin** [comment]
look this https://github.com/jaegertracing/jaeger-client-java/pull/500，update jaeger-client-java 0.30.3
