### ISSUE TITLE
"PoolInitializationException: Failed to initialize pool: Timer already cancelled" for Oracle

### ISSUE THREAD

**Issue by brianrodecap** [opentracing-contrib/java-spring-jaeger#88]
Dependency update from opentracing-spring-jaeger-cloud-starter:3.0.0 to opentracing-spring-jaeger-cloud-starter:3.1.0 or 3.1.1 results in the following error for Oracle data sources from /actuator/health endpoint:

"DataSource health check failed com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Timer already cancelled.
 [90 skipped]
Caused by: java.lang.IllegalStateException: Timer already cancelled.
	at java.base/java.util.Timer.sched(Timer.java:398) ~[na:na]
	at java.base/java.util.Timer.schedule(Timer.java:194) ~[na:na]
	at oracle.net.nt.TimeoutInterruptHandler.scheduleInterrupt(TimeoutInterruptHandler.java:90) ~[ojdbc8-19.3.0.0.jar:19.3.0.0.0]
	at oracle.net.nt.TimeoutInterruptHandler.scheduleInterrupt(TimeoutInterruptHandler.java:103) ~[ojdbc8-19.3.0.0.jar:19.3.0.0.0]
	at oracle.net.nt.TimeoutSocketChannel.scheduleInterrupt(TimeoutSocketChannel.java:235) ~[ojdbc8-19.3.0.0.jar:19.3.0.0.0]
	at oracle.net.nt.TimeoutSocketChannel.connect(TimeoutSocketChannel.java:97) ~[ojdbc8-19.3.0.0.jar:19.3.0.0.0]
	at oracle.net.nt.TimeoutSocketChannel.<init>(TimeoutSocketChannel.java:77) ~[ojdbc8-19.3.0.0.jar:19.3.0.0.0]
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:192) ~[ojdbc8-19.3.0.0.jar:19.3.0.0.0]
	at oracle.net.nt.ConnOption.connect(ConnOption.java:174) ~[ojdbc8-19.3.0.0.jar:19.3.0.0.0]
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:510) ~[ojdbc8-19.3.0.0.jar:19.3.0.0.0]
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:548) ~[ojdbc8-19.3.0.0.jar:19.3.0.0.0]
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:682) ~[ojdbc8-19.3.0.0.jar:19.3.0.0.0]
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:309) ~[ojdbc8-19.3.0.0.jar:19.3.0.0.0]
 [100 skipped]
	... 88 common frames omitted
"

**Comment by geoand** [comment]
Would you be able to provide a reproducer?

Thanks

**Comment by ash1425** [comment]
@geoand 
I have similar issue with Oracle JDBC driver. I have created reproducer repo
https://github.com/ash1425/opentracing-jdbc-issue-reproduce

**Comment by linarkou** [comment]
Any updates? I have the same issue

**Comment by mendreuk** [comment]
The same problem here. Tested on 3.2.2 and still no luck. Fixing this would be highly appreciated.

**Comment by ash1425** [comment]
@geoand It would be great if some contributor can look into it

**Comment by geoand** [comment]
Thanks for the reproducer.

Unfortunately at this moment I am very pressed for time... Hopefully I'll take a look soon.

**Comment by drallen** [comment]
This was fixed by https://github.com/opentracing-contrib/java-jdbc/issues/73 and is available in version 0.2.11 of opentracing-jdbc.  I have tested it with 3.1.1 of this project and it should also work fine with 3.1.2-SNAPSHOT.

**Comment by luizpinheirodev** [comment]
This should resolve this issue:
`implementation('io.opentracing.contrib:opentracing-jdbc') {
        version {
            strictly '0.2.11'
        }
    }`

**Comment by ash1425** [comment]
I can confirm above solution works. Issue can be closed.
